name: Deploy

on:
  workflow_run:
    workflows: ["CI main"]
    types:
      - completed

jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        clean: 'true'
        fetch-depth: 0
    - name: Prepare for release
      run:  |
        export LIB_VERSION=${{ steps.gitversion.outputs.SemVer }}
        pod spec lint
    - name: Release
      run: COCOAPODS_TRUNK_TOKEN=$({ secrets.COCOA_KEY }) pod trunk push
