name: CI pullRequest

on:
  pull_request:
    branches: [ '**' ]  

jobs:
  build_framework:
    runs-on: macos-12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.4.1'
    - uses: actions/checkout@v3
      with:
        clean: 'true'
        fetch-depth: 0
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Run Unit Test
      run: ./Scripts/runTest.sh
    - name: Build Framework
      run: ./Scripts/build.sh
